;(function () {
    angular
        .module('app')
        .config(mainConfig);

    mainConfig.$inject = ['$stateProvider', '$urlRouterProvider', '$translateProvider'];

    function mainConfig($stateProvider, $urlRouterProvider, $translateProvider) {


        $urlRouterProvider.otherwise('/home');

        $stateProvider

            .state('home', {
                url: '/home',
                templateUrl: 'templates/homepage/homepage.html',
                controller: 'HomepageController',
                controllerAs: 'vm'

            })
            .state('technology', {
                url: '/technology',
                templateUrl: 'templates/technology/technology.html',
                controller: 'TechnologyController',
                controllerAs: 'vm'

            })
            .state('about', {
                url: '/about',
                templateUrl: 'templates/about/about.html',
                controller: 'AboutController',
                controllerAs: 'vm'

            })
            .state('contact', {
                url: '/contact',
                templateUrl: 'templates/contact/contact.html',
                controller: 'ContactController',
                controllerAs: 'vm'

            })
            .state('e-commerce', {
                url: '/e-commerce',
                templateUrl: 'templates/e-commerce/e-commerce.html',
                controller: 'ECommerceController',
                controllerAs: 'vm'
            })
            .state('merchant_account', {
                url: '/merchant_account',
                templateUrl: 'templates/merchant_account/merchant_account.html',
                controller: 'MerchantAccountController',
                controllerAs: 'vm'
            })
            .state('merchant_acquiring', {
                url: '/merchant_acquiring',
                templateUrl: 'templates/merchant_acquiring/merchant_acquiring.html',
                controller: 'MerchantAcquiringController',
                controllerAs: 'vm'
            })
            .state('payment_processing', {
                url: '/payment_processing',
                templateUrl: 'templates/payment_processing/payment_processing.html',
                controller: 'PaymentProcessingController',
                controllerAs: 'vm'
            })
            .state('card_issuing', {
                url: '/card_issuing',
                templateUrl: 'templates/card_issuing/card_issuing.html',
                controller: 'CardIssuingController',
                controllerAs: 'vm'
            })
            .state('terms', {
                url: '/terms',
                templateUrl: 'templates/terms/terms.html',
                controller: 'TermsController',
                controllerAs: 'vm'
            })
            .state('cookie', {
                url: '/cookie',
                templateUrl: 'templates/cookie/cookie.html',
                controller: 'CookieController',
                controllerAs: 'vm'
            })
            .state('privacy', {
                url: '/privacy',
                templateUrl: 'templates/privacy/privacy.html',
                controller: 'PrivacyController',
                controllerAs: 'vm'
            })
            .state('prices', {
                url: '/prices',
                templateUrl: 'templates/prices/prices.html',
                controller: 'PricesController',
                controllerAs: 'vm'
            })
            .state('login', {
                url: '/login',
                templateUrl: 'templates/login/login.html',
                controller: 'LoginController',
                controllerAs: 'vm'
            }),




        $translateProvider.registerAvailableLanguageKeys(['en', 'ru'], {
            'en-*': 'en',
            'ru-*': 'ru'
        });
        $translateProvider.translations('en', {

            "solutions": "Solutions",
            "prices": "Prices",
            "about_us": "About us",
            "technology": "Technology",
            "contact_us": "Contact us",
            "language": "en",


            "terms": "Terms",
            "cookie": "Cookie Policy",
            "privacy": "Privacy policy",
            "footer_info": "Since 2018, Araripe ™ is owned by Araripe LTD (UK)",


            "get_started": "Get started",
            "learn_more": "Learn more",
            "our_solutions": "Our solutions",


            "homepage_title": "we make",
            "homepage_subtitle": "ELECTRONIC PAYMENTS SAFE AN EASY",
            "homepage_solution_title": "Full suite of processing solutions for online payments",
            "homepage_solution_subtitle": "Araripe provides a flexible payment processing platform to support all your online payment needs.",
            "homepage_solution_item1_subtitle": "Araripe CORE",
            "homepage_solution_item1_title": "MERCHANT-ACCOUNT",
            "homepage_solution_item1_text": "Start accepting online payments with our essential Merchant Solution.",
            "homepage_solution_item2_subtitle": "Araripe EXPERT",
            "homepage_solution_item2_title": "ONLINE ACQUIRING",
            "homepage_solution_item2_text": "Get on board our flexible and modular Acquiring Solution and manage your online payments more efficiently.",
            "homepage_proactive_title": "Proactive and dedicated",
            "homepage_proactive_item1": "Uninterrupted service",
            "homepage_proactive_item2": "Flexible to adapt to customer",
            "homepage_proactive_item3": "Fast merchant onboarding",
            "homepage_proactive_item4": "Bespoke solutions",
            "homepage_proactive_item5": "Motivated to innovate",
            "homepage_proactive_item6": "Dedicated account manager",
            "homepage_proactive_item7": "Own processing center",
            "homepage_proactive_item8": "24/7 customer support",
            "homepage_carousel_title": "Versatile solutions",
            "homepage_carousel_item1_title": "Wide range of business",
            "homepage_carousel_item2_title": "Wide range of industries",
            "homepage_carousel_item3_title": "Multi-currency processing",
            "homepage_carousel_item4_title": "Secure technologies",
            "homepage_carousel_item5_title": "Global processing",
            "homepage_carousel_item1_text": "Our solutions are tailored for small, medium and large businesses, including merchants, PSP’s, acquirers and issuers",
            "homepage_carousel_item2_text": "Araripes’s fraud prevention and risk management technologies adhere to the highest security standards for online payment services",
            "homepage_carousel_item3_text": "Araripe provides solutions for wide range of industries, including financial, gaming and gambling, Forex, and much more",
            "homepage_carousel_item4_text": "Araripe fraud prevention and risk management technologies adhere to the highest security standards for online payment services",
            "homepage_carousel_item5_text": "Our solutions are designed to support domestic and international processing for online payments across the globe",


            "ecommerce_item1_text2": "Essential and cost-effective payment solution for different e-commerce businesses. Start accepting online payments with our simple starter solution that offer flexibility to expand with your business’ growing requirements.",
            "ecommerce_item2_text2": "Comprehensive and flexible acquiring solution that delivers broad functionality tailored to iPSPs` e-commerce needs. Our modular solution can be customised and adapted to each individual customer and delivered via scalable API.",



            "prices_title": "Price list",
            "prices_text1": "Pay-In:",
            "prices_text2": "3,5% + 0,1 EUR*",
            "prices_list1_text1": "without hidden commission",
            "prices_list1_text2": "no fixed charges",
            "prices_list1_text3": "no connection charges",
            "prices_text3": "The payment fees might be reduced for certain client groups, depending on the companies’ transaction volumes.",
            "prices_text4": "Payment system:",
            "prices_list2_text1": "Bank cards - 3,5% + 0,1 EUR. The commission is charged only for successful transactions. We work with all types of international bank cards such as Visa and MasterCard.",
            "prices_list2_text2": "Yandex money – 3,5%. It is one of the most well-known services of online payment systems in Russia. The payment is done by electronic purse through the currency of Russian ruble.",
            "prices_list2_text3": "QIWI – starting from just 3,5%. QIWI is one of the largest payment services provider.",
            "prices_list2_text4": "WebMoney – starting from just 2%. WebMoney is a global electronic settlement system which conducts payments in a variety of currencies including RUR, EUR and USD.",
            "prices_text5": "Chargeback (the return of funds to a customer): 30 EUR The commission for chargeback processing. ",
            "prices_text6": "Refund: 0,5 EUR Voluntary refund made by merchant to a customer (on their mutual agreement) for the payment submitted previously.",
            "prices_text7": "Payments to the bank cards – starting from 3,0% (the charge is defined on the individual basis depending on the company's type and its transaction volume). Payments are made to the bank cards issued by Russian and European banks.",
            "prices_text8": "Possible options for currency conversion: ",
            "prices_list3_text1": "Conversion is done at the moment when a customer submits the payment and money leaves the customer’s account.",
            "prices_list3_text2": "Conversion is done when the payment is processed by online store.",
            "prices_text9": "Pay-Out:",
            "prices_text10": "2,5% + 5 EUR*",
            "prices_text11": "Our company provides payments to individuals on behalf of legal entities for VISA or MasterCard bank cards and other payment systems. Payouts can be processed to the EU countries and the CIS.",
            "prices_text12": "*The final fee rate is individual",


            "contact_form_title":"FEEDBACK",
            "contact_form_text":"To start working with us, fill in the feedback form to open your merchant account and take advantages of the many benefits Araripe can provide your customers.",
            "contact_form_button":"Send",


            "solution_block_item1_title":"Modular solution",
            "solution_block_item1_text":"Our modular solutions allow you to customise parameters to meet your individual business needs to help you manage transactions more efficiently while reducing the risk and driving revenue growth. Select suitable options from available features to create a truly personalised solution to meet your existing requirements. You can add or remove them as your business changes and expand without hassle and disruption to service.",
            "solution_block_item2_title":"Merchant acquiring services for PSPs and gateway providers",
            "solution_block_item2_text":"With Araripe you can offer your customers comprehensive platform with added benefits and increase their loyalty and retention. Bespoke pricing models allow you to offer competitive merchant services and manage profitable merchant portfolio.",
            "solution_block_item3_title":"Risk Management and Fraud Prevention",
            "solution_block_item3_text":"Our Risk Management and Fraud Prevention services allow you to monitor transactions and set your own parameters for anti-fraud safety measures. A range of restrictions integrated with 3-D Secure allows you to experience efficient fraud protection while maximising numbers of successful transactions.",
            "solution_block_item4_title":"Ongoing support",
            "solution_block_item4_text":"Our priority is to deliver an exceptional customer service by providing 24/7 client support, fast and efficient integration and uninterrupted service. You can rely on our team of experts to provide merchant acquiring services, streamline your processes and operate in a more efficient manner.",

            "benefits_title":"Benefits of using Araripe",
            "benefits_item1_text":"Advanced fraud and risk management",
            "benefits_item2_text":"Chargeback consulting",
            "benefits_item3_text":"Multicurrency processing and payments",
            "benefits_item4_text":"Flexible payment schedule",
            "benefits_item5_text":"Dedicated Account Manager",
            "benefits_item6_text":"24h customer service",
            "benefits_item7_text":"Uninterrupted service",
            "benefits_item8_text":"Fast onbording process",
            "benefits_item9_text":"Scalable platform to meet your business needs",

            "merchant_account_title":"Accepting card payments with Merchant Account solution",
            "merchant_account_subtitle":"We understand how important a decision to accept payments online is for your business as well as fast merchant account sign-up, that’s why Araripe is offering flexible services to fit your requirements.",

            "merchant_acquiring_title":"Advanced and tailored solutions for merchant acquiring",
            "merchant_acquiring_subtitle":"Araripe Expert Acquiring Solution offers technologically advanced payment acquiring services specifically designed to meet diverse needs of Payment Service Providers for merchant acquiring.",
            "merchant_acquiring_text":"We offer multi-currency Acquirer authorisation, clearing and settlement services in 12 currencies across over 30 countries.",

            "about_block":"Never ending technological progress brings higher convenience and efficiency in processes that span the payment industry. We work hard to stay relevant in this constantly changing environment to provide reliable payment services and support to the most demanding clients and businesses.",
            "about_about_text1":"Araripe is an international company providing high-tech services in the field of Internet acquiring to corporate clients around the world.",
            "about_about_text2":"The company's work is based on an individual approach to the requirements of each client, and we are ready to offer our customers only the best-in-class solutions. Our solutions include: modern technologies, processing of online payments, electronic wallets, money transfer services, issue of payment cards, etc. .",
            "about_about_text3":"Araripe is headquartered in London, and has a number of offices in various countries around the world.",
            "about_office_text1":"Araripe  is headquartered in London, in the beating heart of the Fintech industry. Built on the latest technologies, our solutions and services bring so much needed mobility to the financial world. From online payment processing and money transfer services to payment card issuance – we offer everything you need for your online business.",
            "about_office_text2":"And our passion doesn’t end there. The right combination of technical know-how, market expertise and advanced technologies allow us to deliver unique and unrivalled services to our clients and partners worldwide.",
            "about_office_text3":"Araripe is the official service provider for international payment services. Araripe holds the Principal Member status of Visa International and MasterCard Worldwide.",
            "about_map_text1":"countries with implemented projects",
            "about_map_text2":"years team experience in payment industry",
            "about_map_text3":"customers",
            "about_map_value_title":"Brand values",
            "about_map_value_item1_title":"Experience",
            "about_map_value_item1_subtitle":"of our team to exceed client expectations",
            "about_map_value_item2_title":"Flexibility",
            "about_map_value_item2_subtitle":"to adapt to our customers",
            "about_map_value_item3_title":"Innovations",
            "about_map_value_item3_subtitle":"to accelerate leadership in the payment industry",
            "about_map_value_item4_title":"Trust",
            "about_map_value_item4_subtitle":"of our clients as a key to anything we do",
            "about_vision_title":"Company vision",
            "about_vision_text":"Our vision is to become the most reliable business partner and the preferred provider of payment solutions for clients across a wide range of companies and organizations",

            "technology_subtitle":"Every day at Araripe we help our customers to move money safely and securely, processing thousands of transactions and moving money across the world. We are determined to create and deliver solutions for a digital world that is always on.",
            "technology_main_item1_title":"Global",
            "technology_main_item1_text":"We are challenging the industry leaders in developing global payments solutions for businesses that need innovating and adaptive infrastructure to exceed on the ever-changing international and domestic markets. We strive to provide our worldwide partners a platform to allow them to build a global customer base, drive growth and deliver incremental value.",
            "technology_main_item2_title":"Secure and reliable",
            "technology_main_item2_text":"Araripe is Level 1 PSI DSS compliant company and we pride ourselves to provide a safe and secure environment, integrated technology and best-in-class services. With advanced technologies and data centre solutions, we endeavour to provide 99.9% uptime. Our flexible systems are prepared to adapt to a constantly changing environment and continuous innovations in the payment industries.",
            "technology_main_item3_title":"Modular",
            "technology_main_item3_text":"Our modular system is accessible via a comprehensive API and allows customers to choose desirable components to create a truly bespoke service or simply and easily create a complete solution for issuing, acquiring or payment processing. At any time, our customers can change their services by adding or removing specific features, relying on our user-friendly interface and reliable customer support.",
            "technology_main_item4_title":"Connected",
            "technology_main_item4_text":"Our advanced platform allows an easy integration to our API web services or SOAP interface, automated reports delivered on a regular basis and a dedicated data warehouse storage. Our own payment processing centre has a direct connection to authorisation and clearing systems of Visa and MasterCard worldwide. We are regulated by FCA (UK) and operate according to the stringent EU regulations.",
            "technology_list_title":"Araripe features",
            "technology_list_item1_title":"One-click payments",
            "technology_list_item1_text":"One-click payments are perfectly suited for your loyal or repeat customers to pay for goods or services within a second. With Araripe`s one-click payments, you can simplify payments and integrate the PAY NOW button into your website or mobile app, making online shopping as simple as one click",
            "technology_list_item2_title":"Original Credit Transaction (OCT) and Money Send",
            "technology_list_item2_text":"We offer a safe and reliable solution to send money to the customer with only a card number. Our innovative service enables secure money transfers to all Visa and MasterCard accounts allowing processing transaction refund.",
            "technology_list_item3_title":"Payment by link and invoice",
            "technology_list_item3_text":"A simple and convenient feature that enables to create and send customised emails to your customers with a PAY NOW button. The button generates an invoice and lets customers pay by credit and debit card.",
            "technology_list_item4_title":"Recurring billing",
            "technology_list_item4_text":"You will be able to charge a customer a subscription on a repeat basis. The customer will only need to enter the card details once and the payment will be deducted automatically according to the predefined schedule",
            "technology_list_item5_title":"Mail Order and Telephone Order payments",
            "technology_list_item5_text":"Accept payments over the phone or by fax. MOTO is a secure web-based portal that can also work as a virtual POS. You can accept payments from anywhere with only an internet connection.",
            "technology_list_item6_title":"Dynamic Descriptor",
            "technology_list_item6_text":"A dynamic descriptor allows describing a payment to help identify a transaction. Cardholders will get a clearer readability of their bank statements and can easy recognise transactions. Merchants can reduce the risk of chargeback and transaction dispute.",
            "technology_list_item7_title":"Airline Addendum",
            "technology_list_item7_text":"Our Airline Addendum service allows adding additional information regarding airline transaction to the account statement. Full transaction transparency and simplified accounting for companies allow airlines to increase the volume of transactions with corporate cards.",
            "technology_list_item8_title":"Multi-currency processing",
            "technology_list_item8_text":"Araripe accepts multi-currency payments as part of standard processing services. Global customers require merchants to offer flexible payment methods, which creates more opportunities for business growth and international expansion. We offer processing in USD, EUR, GBP, AUD, CHF, DKK, SEK, CAD, NOK, PLN, RUB, CZK and other currencies",
            "technology_list_item9_title":"3D Secure",
            "technology_list_item9_text":"3D Secure is a joint initiative of Visa, MasterCard, and Amex to improve the security of card-not-present transaction processing. This added layer of protection provides safe and secure online payment experience via supplementary password validated by the card issuer.",
            "technology_list_item10_title":"Fraud and Risk Management",
            "technology_list_item10_text":"Our services allow you to monitor transactions and set parameters for anti-fraud safety measures. A range of restrictions integrated with 3-D Secure allows you to experience efficient fraud protection while maximising numbers of successful transactions.",
            "technology_list_item11_title":"Dispute Management and Chargeback Processing",
            "technology_list_item11_text":"Araripe provides Acquirers with dispute management services, including chargeback processing, refunds, and claims to the merchants. We also offer comprehensive reporting and analytical services to help manage and improve card processing functions and decrease costs.",

            "contact_phones_1":"General enquiry",
            "contact_phones_2":"Customer support",
            "contact_pay_title":"Sales & Business Development",
            "contact_pay_item1_title":"Online Acquiring",
            "contact_pay_item2_title":"Payment Processing",
            "contact_pay_item3_title":"Card Issuing",
            "contact_pay_item4_title":"Partner Programme",
            "contact_marketing_title":"Marketing, PR",

            "terms_subtitle":"Last updated: December 05, 2016",
            "terms_text1":"Please read these Terms and Conditions carefully before using the www.araripe.com website (“the Website”) operated by Araripe (“us”, “we”, or “our”).",
            "terms_text2":"Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.",
            "terms_text3":"By accessing or using the Website you agree to be bound by these Terms. If you disagree with any part of the terms you should not use the Website.",
            "terms_title1":"Links To Other Web Sites",
            "terms_text4":"Our Service may contain links to third-party web sites or services that are not owned or controlled by Araripe.",
            "terms_text5":"Araripe has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party web sites or services. You further acknowledge and agree Araripe shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content or services available on or through any such web sites or services.",
            "terms_text6":"We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.",
            "terms_title2":"Governing Law",
            "terms_text7":"These Terms shall be governed and construed in accordance with the laws of United Kingdom, without regard to its conflict of law provisions.",
            "terms_text8":"Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Website, and supersede and replace any prior agreements we might have between us regarding the Service.",
            "terms_title3":"Changes",
            "terms_text9":"We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will post these changes on the Website. It is your sole responsibility to periodically check the Term for any changes. By continuing to access or use our Website after those changes have been made, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Website.",
            "terms_title4":"Copyrights",
            "terms_text10":"You may not reproduce, distribute, modify, or show in public any of the content on this website, including files downloadable from this website, without the permission of the trademark owner.",
            "terms_text11":"Araripe trademark is owned by Araripe",
            "terms_title5":"No warranty",
            "terms_text12":"This website is provided “as is” without any representations or warranties, express or implied. Araripe makes no representations or warranties in relation to this website or the information and materials provided on this website.",
            "terms_text13":"Whilst Araripe will try to ensure that the Website is of highest standard, we do not warrant that this website will be constantly available, or available at all or the information on this website is complete, true, accurate or non-misleading.",
            "terms_text14":"In no event Araripe will be liable for any damages, including, but not limited to direct or indirect damages arising from or in connection with the use of the Website. Nothing on this website constitutes, or is meant to constitute, advice of any kind.",
            "terms_title6":"Indemnity",
            "terms_text15":"You hereby indemnify and undertake to keep Araripe indemnified against any losses, damages, costs, liabilities and expenses (including without limitation legal expenses and any amounts paid by Araripe to a third party in settlement of a claim or dispute on the advice of Araripe’s legal advisers) incurred or suffered by Araripe arising out of any breach by you of any provision of these terms and conditions, or arising out of any claim that you have breached any provision of these terms and conditions.",
            "terms_title7":"Contact Us",
            "terms_text16":"If you have any questions about these Terms, please contact us.",

            "cookie_title": "Cookie Policy for website",
            "cookie_subtitle": "Information about our use of cookies",
            "cookie_text1": "We are using cookies on araripe.com website to improve the website's functionality and provide safer user experience. You can limit the use of cookies at any time by changing your browser settings and deleting the cookies stored.",
            "cookie_strong1":"We process cookies for the following purposes:",
            "cookie_list1_text1":"to remember the parts of site visited by the user to provide engaging content for the site visitors and further disclose issues that are topical for the users;",
            "cookie_list1_text2":"to provide the smooth browsing experience for visitors by verifying and ensuring compatibility of the site with the device and browser version;",
            "cookie_list1_text3":"to maintain the statistics on how often the users visit certain parts of the site, the data is implemented by developers of the site to tailor its usability and enhance the performance.",
            "cookie_strong2":"How to limit the use of cookies?",
            "cookie_text2":"If you don’t want cookies to be used on your devices, you can change the security settings of your browser. Security settings need to be made on each browser individually and the setting methods used may differ.",
            "cookie_strong3":"Where to receive information?",
            "cookie_text3":"If you have any question or suggestion, please call us on:",
            "cookie_text4":"UK: +44 20 3750 2195, EU: +371 63 007 007 or e-mail us on info@araripe.com.",

            "privacy_subtitle": "Araripe (a company registered in England and Wales (company number 09926210) whose registered office is at Suite 3, Third Floor, 62 Bayswater Road, London, W2 3PH) ('We' or 'Us') are committed to protecting and respecting your privacy.",
            "privacy_text1": "This policy (together with our terms of use www.araripe.com/terms and any other documents referred to on it) sets out the basis on which any personal data we collect from you, or that you provide to us, will be processed by us. Please read the following carefully to understand our views and practices regarding your personal data and how we will treat it. By visiting www.araripe.com you are accepting and consenting to the practices described in this policy.",
            "privacy_text2": "For the purpose of the Data Protection Act 1998 (the 'Act'), the data controller is Araripe of Suite 3, Third Floor, 62 Bayswater Road, London, W2 3PH.",
            "privacy_text3": "We are authorised by the Financial Conduct Authority under the Electronic Money Regulations 2011 (FRN: 900592).",
            "privacy_text4": "Part A of this policy governs our use of personal data collected from individuals through their browsing and use of www.araripe.com",
            "privacy_text5": "Part B of this policy sets out the basis on which we will use any personal data collected, or provided, by corporate entities completing and submitting the E-Merchant Application Form.",
            "privacy_section_title1": "Part A - Individuals",
            "privacy_title1": "Information we may collect from you",
            "privacy_text6": "Information we may collect from you",
            "privacy_strong7": "Information you give us.",
            "privacy_text7": "You may give us information about you by filling in forms on our site www.araripe.com ('our site') or by corresponding with us by phone, e-mail or otherwise. This includes information you provide when you register to use our site, subscribe to our service, search for a product, place an order on our site, enter a competition, promotion or a survey, and when you report a problem with our site. The information you give us may include your name, address, e-mail address and phone number, financial and credit card information and personal description.",
            "privacy_strong8": "Information we collect about you.",
            "privacy_text8": "With regard to each of your visits to our site we may automatically collect the following information:",
            "privacy_list1_text1": "technical information, including the Internet protocol (IP) address used to connect your computer to the Internet, your login information, browser type and version, time zone setting, browser plug-in types and versions, operating system and platform;",
            "privacy_list1_text2": "information about your visit, including the full Uniform Resource Locators (URL) clickstream to, through and from our site (including date and time); products you viewed or searched for; page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from the page and any phone number used to call our customer service number.",
            "privacy_strong9": "Information we receive from other sources.",
            "privacy_text9": "We may receive information about you if you use any of the other websites we operate or the other services we provide. We also often work closely with third parties (including, for example, business partners, sub-contractors in technical, payment and delivery services, advertising networks, analytics providers, search information providers, credit reference agencies) and may receive information about you from them.",
            "privacy_title2": "Cookies",
            "privacy_text10": "Our website uses cookies to distinguish you from other users of our website. This helps us to provide you with a good experience when you browse our website and also allows us to improve our site. For detailed information on the cookies we use and the purposes for which we use them see our Cookie policy www.araripe.com/cookie",
            "privacy_title3": "Uses made of the information",
            "privacy_text11":"We use information held about you in the following ways:",
            "privacy_strong12": "Information you give to us.",
            "privacy_text12": "We will use this information:",
            "privacy_list2_text1": "to carry out our obligations arising from any contracts entered into between you and us and to provide you with the information, products and services that you request from us;",
            "privacy_list2_text2": "to provide you with information about other goods and services we offer that are similar to those that you have already purchased or enquired about;",
            "privacy_list2_text3": "to provide you, or permit selected third parties to provide you, with information about goods or services we feel may interest you. If you are an existing customer, we will only contact you by electronic means (e-mail or SMS) with information about goods and services similar to those which were the subject of a previous sale or negotiations of a sale to you. If you are a new customer, and where we permit selected third parties to use your data, we (or they) will contact you by electronic means only if you have consented to this. If you do not want us to use your data in this way, or to pass your details on to third parties for marketing purposes, please tick the relevant box situated on the form on which we collect your data (application form);",
            "privacy_list2_text4": "to notify you about changes to our service; ",
            "privacy_list2_text5": "to ensure that content from our site is presented in the most effective manner for you and for your computer.",
            "privacy_strong13": "Information we collect about you.",
            "privacy_text13": "We will use this information:",
            "privacy_list3_text1": "to administer our site and for internal operations, including troubleshooting, data analysis, testing, research, statistical and survey purposes;",
            "privacy_list3_text2": "to improve our site to ensure that content is presented in the most effective manner for you and for your computer;",
            "privacy_list3_text3": "as part of our efforts to keep our site safe and secure;",
            "privacy_list3_text4": "to measure or understand the effectiveness of advertising we serve to you and others, and to deliver relevant advertising to you;",
            "privacy_list3_text5": "to make suggestions and recommendations to you and other users of our site about goods or services that may interest you or them.",
            "privacy_strong14": "Information we receive from other sources.",
            "privacy_text14": "We may combine this information with information you give to us and information we collect about you. We may use this information and the combined information for the purposes set out above (depending on the types of information we receive).",
            "privacy_title4": "Disclosure of your information",
            "privacy_text15": "We may share your personal information with any member of our group, which means our subsidiaries, our ultimate holding company and its subsidiaries, as defined in section 1159 of the UK Companies Act 2006.",
            "privacy_text16": "We may share your information with selected third parties including:",
            "privacy_list4_text1": "Business partners, suppliers and sub-contractors for the performance of any contract we enter into with them or you.",
            "privacy_list4_text2": "Advertisers and advertising networks that require the data to select and serve relevant adverts to you and others.",
            "privacy_list4_text3": "Analytics and search engine providers that assist us in the improvement and optimisation of our site.",
            "privacy_list4_text4": "Credit reference agencies for the purpose of assessing your credit score where this is a condition of us entering into a contract with you.",
            "privacy_text17": "We may disclose your personal information to third parties:",
            "privacy_list5_text1": "In the event that we sell or buy any business or assets, in which case we may disclose your personal data to the prospective seller or buyer of such business or assets.",
            "privacy_list5_text2": "If Araripe or substantially all of its assets are acquired by a third party, in which case personal data held by it about its customers will be one of the transferred assets.",
            "privacy_list5_text3": "If we are under a duty to disclose or share your personal data in order to comply with any legal obligation, or in order to enforce or apply our terms of use www.araripe.com/terms and other agreements; or to protect the rights, property, or safety of Araripe, our customers, or others. This includes exchanging information with other companies and organisations for the purposes of fraud protection and credit risk reduction.",
            "privacy_title5": "Where we store your personal data",
            "privacy_text18": "The data that we collect from you may be transferred to, and stored at, a destination outside the European Economic Area ('EEA'). It may also be processed by staff operating outside the EEA who work for us or for one of our suppliers. Such staff may be engaged in, among other things, the fulfilment of your order, the processing of your payment details and the provision of support services. By submitting your personal data, you agree to this transfer, storing or processing. We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this privacy policy.",
            "privacy_text19": "All information you provide to us is stored on our secure servers. Any payment transactions will be encrypted using SSL technology. Where we have given you (or where you have chosen) a password which enables you to access certain parts of our site, you are responsible for keeping this password confidential. We ask you not to share a password with anyone.",
            "privacy_text20": "Unfortunately, the transmission of information via the internet is not completely secure. Although we will do our best to protect your personal data, we cannot guarantee the security of your data transmitted to our site; any transmission is at your own risk. Once we have received your information, we will use strict procedures and security features to try to prevent unauthorised access.",
            "privacy_title6": "Your rights",
            "privacy_text21": "You have the right to ask us not to process your personal data for marketing purposes. We will usually inform you (before collecting your data) if we intend to use your data for such purposes or if we intend to disclose your information to any third party for such purposes. You can exercise your right to prevent such processing by checking certain boxes on the forms we use to collect your data. You can also exercise the right at any time by contacting us at [ADDRESS OR E-MAIL ADDRESS].",
            "privacy_text22": "Our site may, from time to time, contain links to and from the websites of our partner networks, advertisers and affiliates. If you follow a link to any of these websites, please note that these websites have their own privacy policies and that we do not accept any responsibility or liability for these policies. Please check these policies before you submit any personal data to these websites.",
            "privacy_title7": "Access to information",
            "privacy_text23": "The Act gives you the right to access information held about you. Your right of access can be exercised in accordance with the Act. Any access request may be subject to a fee of £10 to meet our costs in providing you with details of the information we hold about you.",
            "privacy_title8": "Changes to our privacy policy",
            "privacy_text24": "Any changes we may make to our privacy policy in the future will be posted on this page and, where appropriate, notified to you by e-mail. Please check back frequently to see any updates or changes to our privacy policy.",
            "privacy_title9": "Contact",
            "privacy_text25": "Questions, comments and requests regarding this privacy policy are welcomed and should be addressed to [ADDRESS OR E-MAIL ADDRESS].",
            "privacy_section_title2": "PART B – CORPORATE USE OF THE SITE",
            "privacy_text26": "E-Merchants may use www.araripe.com to submit a form to us containing information on the E-Merchant, the online electronic environment of the E-Merchant including how it offers its goods and services, its bank details, types of goods and services provided and the types of payment card accepted (the 'E-Merchant Application'). The E-Merchant Application also contains personal data including the names and addresses of company directors and shareholders.",
            "privacy_text27": "By submitting the E-Merchant Application, the E-Merchant confirms that it is authorised and, specifically where required by the Act, has the necessary consents to disclose the personal data to us. We shall not be liable for any claim brought by any individual arising from an act or omission resulting from the E-Merchant's failure to ensure that the transfer of the personal data was lawful under the Act.",
            "privacy_text28": "We will use this information to:",
            "privacy_list6_text1": "evaluate the E-Merchant's application to receive our services to support the E-Merchant in its acceptance and processing of card transactions;",
            "privacy_list6_text2": "assess and determine the provisions of an E-Merchant agreement between an E-Merchant and us;",
            "privacy_list6_text3": "enable fraud protection and risk management processes such as checking third party sanctions lists and other databases to ensure that an E-Merchant is eligible to receive our services;",
            "privacy_list6_text4": "manage all billing and invoicing of the E-Merchant;",
            "privacy_list6_text5": "offer the E-Merchant other products and services;",
            "privacy_list6_text6": "comply with our legal compliance obligations.",
            "privacy_text29": "We may share information supplied on the E-Merchant Application with selected third parties such as:",
            "privacy_list7_text1": "payment processors, credit reference and fraud prevention agencies;",
            "privacy_list7_text2": "any person if required by applicable law (including, without limitation, statutory or regulatory reporting obligations.",
            "privacy_text30": "The processing of any payment information on behalf of an E-Merchant is governed by the E-Merchant agreement made between Araripe and the relevant E-Merchant."



        });
        $translateProvider.translations('ru', {

            "solutions": "Решения",
            "prices": "Цены",
            "about_us": "О компании",
            "technology": "Технологии",
            "contact_us": "Контакты",
            "language": "ру",

            "terms": "Условия",
            "cookie": "Политика использования файлов cookie",
            "privacy": "Политика конфиденциальности",
            "footer_info": "2018, Araripe ™ принадлежит компании Araripe LTD (UK)",


            "get_started": "Подключить сервис",
            "learn_more": "Узнать больше",
            "our_solutions": "Наши решения",



            "homepage_title": "мы делаем",
            "homepage_subtitle": "ЭЛЕКТРОННЫЕ ПЛАТЕЖИ БЕЗОПАСНЫми  и ЛЕГКими",
            "homepage_solution_title": "Полный спектр решений для онлайн-платежей и выпуска карт",
            "homepage_solution_subtitle": "Araripe предлагает гибкую платформу для обработки онлайн-платежей, способствующую эффективному развитию Вашего бизнеса в Интернете",
            "homepage_solution_item1_subtitle": "Araripe CORE",
            "homepage_solution_item1_title": "Мерчант аккаунт",
            "homepage_solution_item1_text": "Начните эффективно принимать платежи на своем сайте или в мобильном приложении с помощью нашего решения для интернет-торговцев.",
            "homepage_solution_item2_subtitle": "Araripe EXPERT",
            "homepage_solution_item2_title": "Интернет-эквайринг",
            "homepage_solution_item2_text": "Гибкое и модульное решение для эквайринга обеспечит высокую эффективность Ваших платёжных процессов.",
            "homepage_proactive_title": "Передовые технологии и сервисы",
            "homepage_proactive_item1": "Бесперебойный сервис",
            "homepage_proactive_item2": "Гибкая технология для управления изменениями",
            "homepage_proactive_item3": "Быстрая регистрация торговых счетов",
            "homepage_proactive_item4": "Индивидуально-настроенные решения",
            "homepage_proactive_item5": "Передовые технологии",
            "homepage_proactive_item6": "Индивидуальный менеджер для каждого клиента",
            "homepage_proactive_item7": "Собственный процессинговый центр",
            "homepage_proactive_item8": "Круглосуточная клиентская поддержка",
            "homepage_carousel_title": "Превосходные возможности",
            "homepage_carousel_item1_title": "Различные типы бизнеса",
            "homepage_carousel_item2_title": "Разнообразие индустрий",
            "homepage_carousel_item3_title": "Широкий спектр валют",
            "homepage_carousel_item4_title": "Высокий уровень безопасности",
            "homepage_carousel_item5_title": "Международый процессинг",
            "homepage_carousel_item1_text": "Наши решения поддерживают различные типы бизнеса – от небольших предпринимателей до крупных финансовых учреждений, включая провайдеров платежных сервисов, эквайеров и эмитентов.",
            "homepage_carousel_item2_text": "Araripes предоставляет решения для различных индустрий, таких как путешествия и развлечения, азартные игры и ставки, финансовые и страховые услуги, социальные сети и ИТ-услуги, электронная коммерция",
            "homepage_carousel_item3_text": "В рамках нашего мультивалютного платежного решения мы предлагаем поддержку транзакций в различных валютах (USD, EUR, GBP, AUD, CHF, DKK, SEK, CAD, NOK, PLN, RUB, CZK и др.), помогая упростить процесс перевода денежных средств",
            "homepage_carousel_item4_text": "Технологии Araripe предоставляют эффективную систему для предотвращения мошенничества и управления рисками в соответствии с самыми высокими стандартами безопасности онлайн-платежей",
            "homepage_carousel_item5_text": "Наша компания предоставляет надежную платформу для приёма и обработки внутренних и международных онлайн платежей по всему миру",


            "ecommerce_item1_text2": "Эффективное решение по осуществлению онлайн платежей для малого и среднего бизнеса электронной коммерции. Начните принимать онлайн платежи с помощью нашего оптимального и готового к внедрению решения, которое обеспечит гибкий подход для удовлетворения растущих потребностей Вашего бизнеса.",
            "ecommerce_item2_text2": "Комплекс технологически продвинутых услуг по приёму платежей в Интернете, нацеленных на оптимальное решение различных бизнес-потребностей поставщиков платежных услуг. Наше модульное решение настраивается и адаптируется под нужды каждого клиента и предоставляется через масштабируемый API.",


            "prices_title": "Цены",
            "prices_text1": "Прием денежных средств:",
            "prices_text2": "3,5% + 0,1 EUR*",
            "prices_list1_text1": "без скрытых комиссий",
            "prices_list1_text2": "без абонентской платы",
            "prices_list1_text3": "без платы за подключение",
            "prices_text3": "Комиссия может быть снижена для определенной категории клиентов и в зависимости от вашего оборота.",
            "prices_text4": "Платежные системы:",
            "prices_list2_text1": "Банковские карты – 3,5% + 0,1 EUR. Комиссия берется за каждую успешную оплату. Мы работаем со всеми международными картами типа Visa и MasterCard.",
            "prices_list2_text2": "Яндекс деньги – от 3,5%. Один из самых известных сервисов электронных платежей в России. Электронный кошелек, валютой которого является российский рубль.",
            "prices_list2_text3": "QiWi – от 3,5%. Один из крупных международных платежных сервисов.",
            "prices_list2_text4": "WebMoney – от 2%. Электронная система расчетов, имеющая несколько типов расчетных единиц, основными являются RUR, EUR, USD.",
            "prices_text5": "Чарджбек (возвратный платеж): 30 EUR комиссия берется за процедуру обработки опротестования транзакции.",
            "prices_text6": "Возврат платежа: 0,5 EUR добровольный возврат торговой точкой покупателю платежа, произведенного им ранее по карте в счет покупки.",
            "prices_text7": "Выплаты на банковские карты: от 3,0% (ставка рассчитывается индивидуально в зависимости от вида деятельности компании и оборота). Выплаты осуществляются на карты, эмитированные банками Российской Федерации и Европы.",
            "prices_text8": "Возможные варианты конвертации денежных средств:",
            "prices_list3_text1": "Конвертация на момент списания с карты покупателя.",
            "prices_list3_text2": "Конвертация на момент вывода денежных средств на счет торговой площадки.",
            "prices_text9": "Выплаты денежных средств:",
            "prices_text10": "2,5% + 5 EUR*",
            "prices_text11": "Наша компания осуществляет выплаты физическим лицам по поручению юридических лиц на банковские карты VISA или MasterCard и другие платежные системы. География покрытия ЕС, СНГ и РФ.",
            "prices_text12": "*Финальная ставка определяется индивидуально.",

            "contact_form_title":"ФОРМА ОБРАТНОЙ СВЯЗИ",
            "contact_form_text":"Для начала работы с нами, заполните форму обратной связи, чтобы создать свой аккаунт мерчанта и воспользоваться преимуществами, которые предоставляет клиентам система Araripe.",
            "contact_form_button":"Отправить",


            "solution_block_item1_title":"Модульное и гибкое решение",
            "solution_block_item1_text":"Наше модульное решение поможет удовлетворить индивидуальные потребности Вашего бизнеса, позволяя управлять платежами более эффективно, одновременно снижая риски и повышая прибыль. Выберите функциональность, полностью отвечающую Вашим требованиям, из широкого списка наших предложений, а также с легкостью управляйте этой функциональностью в будущем, в соответствии с растущими бизнес-потребностями.",
            "solution_block_item2_title":"Решение для провайдеров платёжных сервисов",
            "solution_block_item2_text":"С Araripe Интернет-эквайринг Вы сможете предложить своим торговцам комплексную эквайринговую платформу с широкой функциональностью и различными преимуществами. Наша прозрачная модель ценообразования позволит Вам предложить Вашим клиентам привлекательный и конкурентоспособный пакет платёжных услуг, способный повысить эффективность работы и улучшить прибыльность.",
            "solution_block_item3_title":"Предотвращение мошенничества",
            "solution_block_item3_text":"Наша функциональность для управления рисками и система по предотвращению мошенничества позволяют не только контролировать все операции, а также установить индивидуальные параметры для каждой индустрии. Надёжная анти-фрод система с интегрированным стандартом 3D Secure предоставляет эффективную защиту от мошенничества при максимизации числа успешных сделок.",
            "solution_block_item4_title":"Профессиональная поддержка",
            "solution_block_item4_text":"Одним из главных наших приоритетов является предоставление исключительного сервиса нашим клиентам путем оказания круглосуточной 24/7 поддержки, быстрой интеграции и бесперебойного обслуживания. Вы можете довериться нашим профессионалам, которые помогут Вам оптимизировать процессы и более эффективно предоставлять платёжные услуги своим клиентам.",

            "benefits_title":"Преимущества Araripe",
            "benefits_item1_text":"Надёжная система по предотвращению мошенничества",
            "benefits_item2_text":"Помощь в процессе рекламации",
            "benefits_item3_text":"Поддержка широкого спектра валют",
            "benefits_item4_text":"Гибкий график платежей",
            "benefits_item5_text":"Индивидуальный менеджер",
            "benefits_item6_text":"Профессиональная 24/7 поддержка",
            "benefits_item7_text":"Бесперебойный сервис",
            "benefits_item8_text":"Быстрая и эффективная интеграция",
            "benefits_item9_text":"Гибкая платформа, настроенная под Ваши индивидуальные потребности",

            "merchant_account_title":"Мерчант аккаунт для приёма платежей на сайтах интернет-торговцев",
            "merchant_account_subtitle":"Мы понимаем, насколько важна для Вашего бизнеса возможность приёма платежей на сайте, а также быстрое открытие мерчант аккаунта, поэтому Araripe предлагает гибкие, конкурентоспособные решения, разработанные в соответствии с Вашими индивидуальными требованиями.",

            "merchant_acquiring_title":"Гибкий и передовой интернет-эквайринг",
            "merchant_acquiring_subtitle":"Araripe Expert Интернет-эквайринг предлагает платёжную платформу, специально предназначенную для удовлетворения разнообразных потребностей провайдеров платежных услуг (iPSP).",
            "merchant_acquiring_text":"Мы предлагаем мультивалютные платежи, а также клиринговые и расчетные услуги в 12 валютах более чем в 30 странах.",

            "about_block":"Технологическое развитие платежной индустрии делает большой акцент на инновациях, удобстве, а также повышении эффективности процессов. Находясь в среде постоянно меняющихся тенденций, нам удалось создать надёжную систему, способную обеспечивать мощную поддержку бизнеса наших клиентов.",
            "about_about_text1":"Araripe – международная компания, предоставляющая высокотехнологичные услуги в сфере интернет-эквайринга корпоративным клиентам по всему миру.",
            "about_about_text2":"Работа компании основана на индивидуальном подходе к требованиям каждого клиента, и мы готовы предложить нашим клиентам только лучшие в своем классе решения.Наши решения включают в себя: современные технологии, процессинг онлайн-платежей, электронные кошельки, услуги перевода денег, выпуск платёжных карт и др.",
            "about_about_text3":"Компания Araripe представлена головным офисом в Лондоне, а также имеющая ряд офисов в различных странах по всему миру.",
            "about_office_text1":"Компания Araripe представлена головным офисом в Лондоне, и мы гордимся тем, что находимся в самом центре Fintech-индустрии. Наши решения включают в себя современные технологии, привносящие мобильность в финансовый мир и объединяют такие услуги, как процессинг онлайн-платежей, электронные кошельки, услуги перевода денег, выпуск платёжных карт и др.",
            "about_office_text2":"Наши амбиции на этом не заканчиваются. Мы стремимся предоставлять современные решения, основанные на передовых технологиях и ноу-хау. Мы идем в ногу со временем в сфере новейших платёжных и карточных решений, а успех нашей компании — это идеальное сочетание современных технологий, надежного сервиса и профессиональной команды.",
            "about_office_text3":"Araripe является официальным сервис-провайдером международных платежных систем Visa International и MasterCard Worldwide, а также обладает статусом Principal Member.",
            "about_map_text1":"стран с осуществлёнными проектами",
            "about_map_text2":"лет командного опыта в платёжной индустрии",
            "about_map_text3":"клиентов",
            "about_map_value_title":"Основные ценности",
            "about_map_value_item1_title":"Опыт",
            "about_map_value_item1_subtitle":"команды, превосходящий ожидания клиентов",
            "about_map_value_item2_title":"Гибкость",
            "about_map_value_item2_subtitle":"решений для удовлетворения требований клиентов",
            "about_map_value_item3_title":"Инновации",
            "about_map_value_item3_subtitle":"и лидерство в сфере платёжных технологий",
            "about_map_value_item4_title":"Доверие",
            "about_map_value_item4_subtitle":"клиентов, как ключевой принцип нашей деятельности",
            "about_vision_title":"Видение компании Araripe",
            "about_vision_text":"Наше видение – стать самым надежным деловым партнером и предпочтительным поставщиком платёжных решений для различных организаций и компаний, позволяя им успешно конкурировать и динамично развиваться в условиях современного рынка ",

            "technology_subtitle":"Процессинговый центр Araripe обрабатывает сотни тысяч транзакций каждый день для компаний по всему миру. Предоставляя обширный спектр сервисов для онлайн-бизнесов, компания помогает открывать мир платежей с невероятно удобной и выгодной стороны",
            "technology_main_item1_title":"Глобальность",
            "technology_main_item1_text":"Наше постоянное стремление к передовым технологиям остается одним из основных пунктов нашей стратегии, а постоянно расширяющееся портфолио наших сервисов при поддержке команды высокопрофессиональных специалистов, предоставляет нашим клиентам и партнерам платформу, которая обеспечивает для них новые возможности развития бизнеса по всему миру.",
            "technology_main_item2_title":"Надёжность и безопасность",
            "technology_main_item2_text":"Уделяя максимум внимания таким аспектам, как безопасность, соответствие требованиям рынка и профессиональная поддержка, мы гордимся тем, что можем предложить нашим клиентам надежную и безопасную среду для процессинга карт и платежей в соответствии со стандартом PCI DSS Level 1. Используя передовые технологии, мы гарантируем бесперебойную работу на 99,99%.",
            "technology_main_item3_title":"Модульная система",
            "technology_main_item3_text":"Сделайте Ваш бизнес проще с нашей модульной системой, которая предоставляет широкий спектр функциональности и легко управляется при помощи API, адаптируясь к постоянно меняющимся бизнес-требованиям. Наша адаптивная инфраструктура, а также надежная поддержка клиентов легко позволит Вам ориентировать Ваш бизнес на принятие новых тенденций по мере их появления.",
            "technology_main_item4_title":"Постоянная связь",
            "technology_main_item4_text":"Процессинговый центр Araripe обеспечивает высокое качество обслуживания финансовых операций и предоставляет прямое подключение к системам авторизации и клиринга Visa и MasterCard по всему миру. Для решения задач наших клиентов мы создали масштабируемую платформу, которая гарантирует простую интеграцию через приложение API или SOAP интерфейсы.",
            "technology_list_title":"Функциональность Araripe",
            "technology_list_item1_title":"Платёж в один клик",
            "technology_list_item1_text":"Платеж в один клик поддерживает технологию мгновенной оплаты и идеально подходит для Ваших постоянных клиентов, позволяя производить оплату товаров или услуг в течение секунды",
            "technology_list_item2_title":"Выплаты на карту Visa Direct Original Credit Transaction (OCT) и Money Send",
            "technology_list_item2_text":"Мы предлагаем безопасное и надежное решение для переводов денег своим клиентам, используя только номер карты. Наш инновационный сервис обеспечивает денежные переводы для всех счетов Visa и MasterCard и позволяет моментально пополнять баланс банковских карт.",
            "technology_list_item3_title":"Платёж по линку и инвойсу",
            "technology_list_item3_text":"Простая и удобная функция, которая позволяет создавать и отправлять своим клиентам индивидуальные электронные письма с внутренней ссылкой на оплату. Нажатие ссылки позволяет сгенерировать инвойс и провести платеж при помощи кредитной или дебетовой карты.",
            "technology_list_item4_title":"Рекуррентные платежи (рекаринг)",
            "technology_list_item4_text":"Платёж может взиматься на повторяющейся основе. Клиент должен ввести данные карты только один раз, после чего платеж будет производиться автоматически в соответствии с предопределенным графиком.",
            "technology_list_item5_title":"МОТО платежи",
            "technology_list_item5_text":"Прием платежей по телефону или по факсу. MOTO - это защищенный веб-портал, который также может работать, как виртуальный POS. Вы можете принимать платежи из любой точки мира, имея лишь подключение к Интернету.",
            "technology_list_item6_title":"Динамический дескриптор",
            "technology_list_item6_text":"Динамический дескриптор позволяет создавать дополнительное описание для платежа, чтобы помочь идентифицировать транзакцию. Владельцы карт получают более подробное описание своих банковских выписок и могут легко распознавать транзакции. В свою очередь, торговцы могут существенно снизить риск возникновения споров о возврате платежей и транзакций.",
            "technology_list_item7_title":"Длинная запись для авиа Airline Addendum",
            "technology_list_item7_text":"Длинная запись для авиа Airline Addendum позволяет добавлять дополнительную информацию о маршруте полета, который вместе с транзакцией отправляется в платежную систему для обработки. Использование этих данных обеспечивает прозрачность операции и упрощенный учет, а также снижает риск мошеннических операций.",
            "technology_list_item8_title":"Мультивалютный процессинг интернет платежей",
            "technology_list_item8_text":"Мультивалютный процессинг интернет платежей, предоставляемый компанией Araripe, обеспечивает приём платежей по всему миру и предлагает гибкие способы оплаты в различных валютах - USD, EUR, GBP, AUD, CHF, DKK, SEK, CAD, NOK, PLN, RUB, CZK и др., тем самым создавая превосходные возможности для роста бизнеса по всему миру.",
            "technology_list_item9_title":"Технология безопасности 3D Secure",
            "technology_list_item9_text":"Являясь частью совместной инициативы глобальных программ MasterCard® SecureCode™ и Verified by Visa, технология 3D Secure позволяет обеспечить безопасные платежи в интернете и максимально снизить риск мошенничества путём идентификации подлинности держателя карты.",
            "technology_list_item10_title":"Система по управлению рисками и предотвращению мошенничества",
            "technology_list_item10_text":"Решение по предотвращению мошенничества представляет собой платформу, позволяющую выявлять и предотвращать факты мошенничества при расчетах в интернете, идентифицируя подозрительные и мошеннические транзакции. Функциональность решения позволяет разработать индивидуальные условия управления рисками, тем самым повышая число успешных транзакций.",
            "technology_list_item11_title":"Разрешение спорных транзакций",
            "technology_list_item11_text":"Araripe предоставляет услуги по рекламации и разрешению спорных транзакций, включая обработку возвратных платежей, возврат средств, а также помощь в рассмотрении претензий к торговцам. Мы также предоставляем комплексную систему отчетности, которая позволяет улучшить процесс обработки платежей, а также снизить затраты.",

            "contact_phones_1":"Основные контакты",
            "contact_phones_2":"Клиентская поддержка",
            "contact_pay_title":"Отдел продаж",
            "contact_pay_item1_title":"Интернет-эквайринг",
            "contact_pay_item2_title":"Процессинг платежей",
            "contact_pay_item3_title":"Эмиссия карт",
            "contact_pay_item4_title":"Партнерская программа",
            "contact_marketing_title":"Маркетинг, связи с общественностью",

            "terms_subtitle":"Последнее обновление: 05 декабря 2016 г.",
            "terms_text1":"Пожалуйста, внимательно прочитайте настоящие Условия и положения, прежде чем пользоваться сайтом www.araripe.com («Веб-сайт»), которым управляет Araripe («мы», «мы» или «наш»).",
            "terms_text2":"Ваш доступ к Сервису и его использование зависит от вашего согласия и соблюдения этих Условий. Эти Условия распространяются на всех посетителей, пользователей и других лиц, которые пользуются или пользуются Сервисом.",
            "terms_text3":"Получая доступ к Сайту или используя его, вы соглашаетесь соблюдать настоящие Условия. Если вы не согласны с какой-либо частью условий, вы не должны использовать Веб-сайт.",
            "terms_title1":"Ссылки на другие веб-сайты",
            "terms_text4":"Наша Служба может содержать ссылки на сторонние веб-сайты или службы, которые не принадлежат или не контролируются Araripe.",
            "terms_text5":"Araripe не контролирует и не несет никакой ответственности за контент, политику конфиденциальности или действия сторонних веб-сайтов или служб. Вы также подтверждаете и соглашаетесь, что Araripe не несет прямой или косвенной ответственности за любой ущерб или убытки, вызванные или предположительно вызванные или связанные с использованием или использованием какого-либо такого контента или услуг, доступных на веб-сайтах или услугах.",
            "terms_text6":"Мы настоятельно рекомендуем вам ознакомиться с условиями и политикой конфиденциальности любых сторонних веб-сайтов или служб, которые вы посещаете.",
            "terms_title2":"Применимое право",
            "terms_text7":"Настоящие Условия регулируются и толкуются в соответствии с законодательством Соединенного Королевства, независимо от его положений, касающихся коллизионного права.",
            "terms_text8":"Наш отказ в соблюдении любого права или положения настоящих Условий не будет считаться отказом от этих прав. Если какое-либо положение настоящих Условий считается недействительным или не имеющим законной силы судом, остальные положения настоящих Условий останутся в силе. Эти Условия составляют полное соглашение между нами относительно нашего Веб-сайта и заменяют любые предыдущие соглашения, которые мы могли бы иметь между нами в отношении Сервиса.",
            "terms_title3":"Изменения",
            "terms_text9":"Мы оставляем за собой право по собственному усмотрению изменять или заменять эти Условия в любое время. Мы опубликуем эти изменения на Сайте. Вы несете отдельную ответственность за периодическую проверку Свода за любые изменения. Продолжая доступ к сайту или его использование после того, как эти изменения были внесены, вы соглашаетесь соблюдать пересмотренные условия. Если вы не согласны с новыми условиями, прекратите использовать Веб-сайт.",
            "terms_title4":"Авторские права",
            "terms_text10":"Вы не имеете права воспроизводить, распространять, изменять или публиковать любой контент на этом веб-сайте, включая файлы, загружаемые с этого веб-сайта, без разрешения владельца товарного знака.",
            "terms_text11":"Торговая марка Araripe принадлежит Araripe",
            "terms_title5":"Нет гарантии",
            "terms_text12":"Этот веб-сайт предоставляется «как есть» без каких-либо заявлений или гарантий, явных или подразумеваемых. Araripe не делает никаких заявлений или гарантий в отношении этого веб-сайта или информации и материалов, представленных на этом веб-сайте.",
            "terms_text13":"В то время как Araripe постарается обеспечить, чтобы Веб-сайт был самым высоким стандартом, мы не гарантируем, что этот веб-сайт будет постоянно доступен или доступен вообще или информация на этом веб-сайте является полной, достоверной, точной или не вводимой в заблуждение.",
            "terms_text14":"Ни при каких обстоятельствах Araripe не несет ответственности за любые убытки, включая, но не ограничиваясь прямым или косвенным ущербом, возникшим в связи с использованием Веб-сайта или в связи с ним. Ничто на этом веб-сайте не является или не предназначено для каких-либо советов.",
            "terms_title6":"Контрибуция",
            "terms_text15":"Вы настоящим возмещаете и обязываетесь удерживать Araripe от любых убытков, убытков, расходов, обязательств и расходов (включая, без ограничений, судебные издержки и любые суммы, уплаченные Araripe третьему лицу при урегулировании иска или спора по рекомендации юридического лица Araripe советники), понесенные или пострадавшие от Araripe, возникшие в результате любого нарушения вами какого-либо положения настоящих условий или вытекающие из любого требования, что вы нарушили какое-либо положение этих условий.",
            "terms_title7":"Свяжитесь с нами",
            "terms_text16":"Если у вас есть какие-либо вопросы об этих Условиях, свяжитесь с нами.",

            "cookie_title": "Политика использования файлов cookie",
            "cookie_subtitle": "Использование файлов Cookies",
            "cookie_text1": "Мы используем файлы cookies на портале araripe.com, которые помогают нам улучшить функциональность и обеспечить безопасные условия пользования сайтом. В любое время Вы можете ограничить их использование, изменив настройки браузера и удалив сохраненные файлы.",
            "cookie_strong1":"Общие цели использования cookie файлов являются следующими:",
            "cookie_list1_text1":"запомнить разделы сайта, которые посетил пользователь, чтобы предоставить посетителям сайта интересное содержание и впредь публиковать актуальные пользователю темы;",
            "cookie_list1_text2":"обеспечить посетителям равномерную навигацию, проверив и обеспечив совместимость сайта с версией устройства и версией веб-браузера;",
            "cookie_list1_text3":"поддерживать статистику, насколько часто пользователи посещают конкретные разделы сайта; разработчики сайта используют указанные данные для повышения удобства в использовании и улучшения работы сайта.",
            "cookie_strong2":"Как ограничить использование файлов cookies?",
            "cookie_text2":"Если вы желаете, чтобы в ваших устройствах не использовались файлы cookie, вы можете изменить настройки безопасности своего браузера. Настройки необходимо изменить для каждого браузера отдельно и применяемые методы настроек могут отличаться.",
            "cookie_strong3":"Где можно получить информацию?",
            "cookie_text3":"Если у вас появились вопросы или предложения, просим звонить по телефону:",
            "cookie_text4":"UK: +44 20 3750 2195, EU: +371 63 007 007 или писать на адрес электронной почты info@araripe.com.",

            "privacy_subtitle": "Araripe (компания, зарегистрированная в Англии и Уэльсе (номер компании 09926210), чей зарегистрированный офис находится в Suite 3, Third Floor, 62 Bayswater Road, London, W2 3PH) («Мы» или «Мы») обязуемся защищать и уважать ваши Конфиденциальность.",
            "privacy_text1": "В этой политике (вместе с нашими условиями использования www.araripe.com/terms и любыми другими документами, указанными на ней) определяется основа, по которой любые личные данные, которые мы собираем у вас или которые вы предоставляете нам, будут обрабатываться нас. Пожалуйста, внимательно прочитайте следующее, чтобы понять наши взгляды и практики в отношении ваших персональных данных и как мы будем относиться к ним. Посетив www.araripe.com, вы принимаете и соглашаетесь с практикой, описанной в этой политике.",
            "privacy_text2": "Для целей Закона о защите данных 1998 года («Закон») контроллер данных Araripe Suite 3, Третий этаж, 62 Bayswater Road, Лондон, W2 3PH.",
            "privacy_text3": "Мы уполномочены Управлением финансового поведения в соответствии с Правилами электронных денег 2011 года (FRN: 900592).",
            "privacy_text4": "Часть A этой политики регулирует наше использование персональных данных, собранных от людей, через их просмотр и использование www.araripe.com",
            "privacy_text5": "В части B этой политики излагается основа, по которой мы будем использовать любые личные данные, собранные или предоставленные корпоративными организациями, заполняющими и подающими форму заявки на электронный коммерс.",
            "privacy_section_title1": "Часть A - Физические лица",
            "privacy_title1": "Информация, которую мы можем собирать у вас",
            "privacy_text6": "Информация, которую мы можем собирать у вас",
            "privacy_strong7": "Информация, которую вы нам даете.",
            "privacy_text7": "Вы можете предоставить нам информацию о вас, заполнив бланки на нашем сайте www.araripe.com («наш сайт») или связавшись с нами по телефону, электронной почте или иным образом. Это включает информацию, которую вы предоставляете, когда вы регистрируетесь для использования нашего сайта, подписаться на нашу услугу, искать продукт, размещать заказ на нашем сайте, участвовать в конкурсе, продвижении по службе или опросе, а также сообщать о проблеме с нашим сайтом. Информация, которую вы нам даете, может включать ваше имя, адрес, адрес электронной почты и номер телефона, информацию о финансовой и кредитной карте и личное описание.",
            "privacy_strong8": "Информация, которую мы собираем о вас.",
            "privacy_text8": "Что касается каждого из ваших посещений нашего сайта, мы можем автоматически собрать следующую информацию:",
            "privacy_list1_text1": "техническую информацию, включая адрес интернет-протокола (IP), используемый для подключения вашего компьютера к Интернету, данные вашего входа, тип и версию браузера, настройки часового пояса, типы и версии подключаемого модуля браузера, операционную систему и платформу;",
            "privacy_list1_text2": "информацию о вашем посещении, включая полный URL-адрес Единого указателя ресурса (URL), через и с нашего сайта (включая дату и время); продукты, которые вы просматривали или искали; время отклика страницы, ошибки загрузки, продолжительность посещений определенных страниц, информация о взаимодействии страниц (например, прокрутка, клики и мыши), а также методы, используемые для просмотра страницы и любого номера телефона, используемого для вызова нашего номера обслуживания клиентов ,",
            "privacy_strong9": "Информация, которую мы получаем из других источников.",
            "privacy_text9": "Мы можем получать информацию о вас, если вы используете какой-либо другой веб-сайт, который мы используем, или другие услуги, которые мы предоставляем. Мы также часто работаем в тесном контакте с третьими лицами (включая, например, деловых партнеров, субподрядчиков в технических службах, платежах и доставке, рекламных сетях, поставщиках аналитики, поставщиках поисковых данных, кредитных справочных агентствах) и могут получать от вас информацию о вас.",
            "privacy_title2": "Файлы Cookie",
            "privacy_text10": "Наш сайт использует файлы cookie, чтобы отличать вас от других пользователей нашего сайта. Это помогает нам предоставить вам хороший опыт при просмотре нашего сайта, а также позволяет нам улучшить наш сайт. Для получения подробной информации о файлах cookie, которые мы используем, и целях, для которых мы их используем, см. Нашу политику в отношении файлов cookie www.araripe.com/cookie.",
            "privacy_title3": "Использование информации",
            "privacy_text11":"Мы используем информацию о вас следующими способами:",
            "privacy_strong12": "Информация, которую вы нам дарите.",
            "privacy_text12": "Мы будем использовать эту информацию:",
            "privacy_list2_text1": "выполнять наши обязательства, вытекающие из любых договоров, заключенных между вами и нами, и предоставлять вам информацию, продукты и услуги, которые вы запрашиваете у нас;",
            "privacy_list2_text2": "предоставить вам информацию о других товарах и услугах, которые мы предлагаем, которые аналогичны тем, которые вы уже приобрели или интересуетесь;",
            "privacy_list2_text3": "предоставить вам или разрешить отдельным третьим сторонам предоставить вам информацию о товарах или услугах, которые, как мы считаем, могут вас заинтересовать. Если вы являетесь существующим клиентом, мы свяжемся с вами только электронными средствами (электронной почтой или SMS) с информацией о товарах и услугах, аналогичных тем, которые были предметом предыдущей продажи или переговоров о продаже вам. Если вы новый клиент и где мы разрешаем выбранным третьим лицам использовать ваши данные, мы (или они) свяжемся с вами электронными средствами, только если вы согласились на это. Если вы не хотите, чтобы мы использовали ваши данные таким образом или передали ваши данные третьим сторонам в целях маркетинга, отметьте соответствующее поле, расположенное в форме, на которой мы собираем ваши данные (форму заявки);",
            "privacy_list2_text4": "уведомить вас об изменениях в нашем сервисе;",
            "privacy_list2_text5": "чтобы контент с нашего сайта был представлен наиболее эффективным образом для вас и для вашего компьютера.",
            "privacy_strong13": "Информация, которую мы собираем о вас.",
            "privacy_text13": "Мы будем использовать эту информацию:",
            "privacy_list3_text1": "для администрирования нашего сайта и для внутренних операций, включая поиск и устранение неисправностей, анализ данных, тестирование, исследования, статистические и исследовательские цели;",
            "privacy_list3_text2": "улучшить наш сайт, чтобы убедиться, что контент представлен наиболее эффективным образом для вас и для вашего компьютера;",
            "privacy_list3_text3": "как часть наших усилий по обеспечению безопасности и безопасности нашего сайта;",
            "privacy_list3_text4": "измерять или понимать эффективность рекламы, которую мы обслуживаем для вас и других, и предоставлять вам соответствующую рекламу;",
            "privacy_list3_text5": "делать предложения и рекомендации для вас и других пользователей нашего сайта о товарах или услугах, которые могут вас заинтересовать или вас.",
            "privacy_strong14": "Информация, которую мы получаем из других источников.",
            "privacy_text14": "Мы можем объединить эту информацию с информацией, которую вы нам даете, и информацией, которую мы собираем о вас. Мы можем использовать эту информацию и общую информацию для целей, изложенных выше (в зависимости от типов информации, которую мы получаем).",
            "privacy_title4": "Раскрытие вашей информации",
            "privacy_text15": "Мы можем передавать вашу личную информацию любому члену нашей группы, что означает наши дочерние компании, нашу конечную холдинговую компанию и ее дочерние компании, как это определено в разделе 1159 Закона о компаниях Великобритании 2006 года.",
            "privacy_text16": "Мы можем поделиться вашей информацией с выбранными третьими лицами, включая:",
            "privacy_list4_text1": "Деловые партнеры, поставщики и субподрядчики для выполнения любого контракта, с которым мы заключаем их с вами или вами.",
            "privacy_list4_text2": "Рекламодатели и рекламные сети, которым требуются данные для выбора и обслуживания релевантных объявлений вам и другим.",
            "privacy_list4_text3": "Аналитики и поставщики поисковых систем, которые помогают нам в улучшении и оптимизации нашего сайта.",
            "privacy_list4_text4": "Кредитные справочные агентства с целью оценки вашего кредитного балла, если это условие того, что мы заключили с вами договор.",
            "privacy_text17": "Мы можем раскрыть вашу личную информацию третьим лицам:",
            "privacy_list5_text1": "В случае, если мы продаем или покупаем какой-либо бизнес или активы, в этом случае мы можем раскрыть ваши личные данные потенциальному продавцу или покупателю такого бизнеса или активов.",
            "privacy_list5_text2": "Если Araripe или практически все ее активы приобретены третьей стороной, в этом случае личные данные, хранящиеся в ней о своих клиентах, будут одним из переданных активов.",
            "privacy_list5_text3": "Если мы обязаны раскрывать или передавать ваши личные данные для соблюдения любого юридического обязательства или для обеспечения соблюдения или применения наших условий использования www.araripe.com/terms и других соглашений; или для защиты прав, имущества или безопасности Araripe, наших клиентов или других лиц. Это включает обмен информацией с другими компаниями и организациями в целях защиты от мошенничества и снижения кредитного риска.",
            "privacy_title5": "Где мы храним ваши личные данные",
            "privacy_text18": "Данные, которые мы собираем от вас, могут быть переданы и сохранены в пункте назначения за пределами Европейской экономической зоны («ЕАОС»). Он также может обрабатываться сотрудниками, работающими за пределами ЕАОС, которые работают для нас или для одного из наших поставщиков. Такие сотрудники могут участвовать, помимо прочего, в выполнении вашего заказа, обработке ваших платежных реквизитов и предоставлении вспомогательных услуг. Предоставляя свои личные данные, вы соглашаетесь на эту передачу, хранение или обработку. Мы предпримем все необходимые меры для обеспечения надежной обработки ваших данных и в соответствии с этой политикой конфиденциальности.",
            "privacy_text19": "Вся информация, которую вы предоставляете нам, хранится на наших защищенных серверах. Любые платежные операции будут зашифрованы с использованием технологии SSL. Если мы предоставили вам (или где вы выбрали) пароль, который позволяет вам получить доступ к определенным частям нашего сайта, вы несете ответственность за сохранение этого пароля. Мы просим вас не делиться паролем ни с кем.",
            "privacy_text20": "К сожалению, передача информации через Интернет не полностью безопасна. Хотя мы сделаем все возможное для защиты ваших личных данных, мы не можем гарантировать безопасность ваших данных, передаваемых на наш сайт; любая передача на свой страх и риск. Как только мы получим вашу информацию, мы будем использовать строгие процедуры и функции безопасности, чтобы попытаться предотвратить несанкционированный доступ.",
            "privacy_title6": "Ваши права",
            "privacy_text21": "Вы имеете право попросить нас не обрабатывать ваши личные данные в целях маркетинга. Обычно мы сообщим вам (прежде чем собирать ваши данные), если мы намерены использовать ваши данные для таких целей или если мы намерены раскрыть вашу информацию какой-либо третьей стороне для таких целей. Вы можете реализовать свое право на предотвращение такой обработки, проверив определенные поля форм, которые мы используем для сбора ваших данных. Вы также можете воспользоваться правом в любое время, связавшись с нами по адресу [АДРЕС ИЛИ АДРЕС ЭЛЕКТРОННОЙ ПОЧТЫ].",
            "privacy_text22": "Наш сайт может время от времени содержать ссылки на сайты партнерских сетей, рекламодателей и аффилированных лиц. Если вы следуете ссылке на любой из этих веб-сайтов, обратите внимание, что эти веб-сайты имеют свои собственные политики конфиденциальности и что мы не несем никакой ответственности или ответственности за эти политики. Прежде чем отправлять какие-либо личные данные на эти веб-сайты, ознакомьтесь с этими правилами.",
            "privacy_title7": "Доступ к информации",
            "privacy_text23": "Закон дает вам право доступа к информации о вас. Ваше право на доступ может осуществляться в соответствии с Законом. В любом запросе на доступ может взиматься плата в размере 10 фунтов стерлингов, чтобы покрыть наши расходы, предоставляя вам подробную информацию о вас.",
            "privacy_title8": "Изменения в нашей политике конфиденциальности",
            "privacy_text24": "Любые изменения, которые мы можем внести в нашу политику конфиденциальности в будущем, будут опубликованы на этой странице и, при необходимости, будут отправлены вам по электронной почте. Повторите попытку, чтобы увидеть какие-либо обновления или изменения в нашей политике конфиденциальности.",
            "privacy_title9": "Контакты",
            "privacy_text25": "Вопросы, комментарии и запросы в отношении этой политики конфиденциальности приветствуются и должны быть адресованы [АДРЕСУ ИЛИ АДРЕС E-MAIL].",
            "privacy_section_title2": "ЧАСТЬ B - КОРПОРАТИВНОЕ ИСПОЛЬЗОВАНИЕ САЙТА",
            "privacy_text26": "E-Merchants могут использовать www.araripe.com, чтобы отправить нам форму, содержащую информацию о E-Merchant, электронной электронной среде электронного торговца, в том числе о том, как она предлагает свои товары и услуги, ее банковские реквизиты, типы товаров и предоставляемые услуги и типы принятых платежных карт («Приложение E-Merchant»). Приложение E-Merchant также содержит личные данные, включая имена и адреса директоров и акционеров компании.",
            "privacy_text27": "Предоставляя E-Merchant Application, E-Merchant подтверждает, что оно разрешено и, в частности, в случае необходимости в соответствии с Законом, имеет необходимые согласия, чтобы раскрыть нам персональные данные. Мы не несем ответственности за любое требование, предъявленное каким-либо лицом, возникшее в результате действия или бездействия, вызванного неспособностью электронного торговца обеспечить, чтобы передача персональных данных была законной в соответствии с Законом.",
            "privacy_text28": "Мы будем использовать эту информацию для:",
            "privacy_list6_text1": "оценить приложение E-Merchant для получения наших услуг для поддержки E-Merchant при его принятии и обработке транзакций с карточками;",
            "privacy_list6_text2": "оценивать и определять положения соглашения E-Merchant между E-Merchant и нами;",
            "privacy_list6_text3": "включить процедуры защиты от мошенничества и управления рисками, такие как проверка списков санкций сторонних организаций и других баз данных, чтобы гарантировать, что E-Merchant имеет право на получение наших услуг;",
            "privacy_list6_text4": "управлять всем выставлением счетов и выставлением счетов E-Merchant;",
            "privacy_list6_text5": "предлагать E-Merchant другие продукты и услуги;",
            "privacy_list6_text6": "comply with our legal compliance obligations.",
            "privacy_text29": "Мы можем обмениваться информацией, представленной в E-Merchant Application, с выбранными третьими лицами, такими как:",
            "privacy_list7_text1": "платежные системы, агентства по предоставлению кредитных справок и мошенничества;",
            "privacy_list7_text2": "любое лицо, если это требуется применимым законодательством (включая, помимо прочего, обязательные или нормативные обязательства по отчетности.",
            "privacy_text30": "Обработка любой платежной информации от имени E-Merchant регулируется Соглашением E-Merchant, заключенным между Araripe и соответствующим E-Merchant."

        });

        // $translateProvider.useStaticFilesLoader({
        //     prefix: 'language/',
        //     suffix: '.json'
        // });

        $translateProvider.preferredLanguage('en');
        $translateProvider.useSanitizeValueStrategy(null);
    }



})();

